# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-08 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_question_number_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
    ]
