# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-08 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190508_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='correct_answer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
