# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 13:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_choice_correct_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='correct_answer',
            new_name='is_correct_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)]))]),
        ),
        migrations.AlterField(
            model_name='question',
            name='number_responses',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
